import React, { useState } from "react";

const ChemistBillUpload = () => {
  const [bill, setBill] = useState(null);
  const [verified, setVerified] = useState(false);

  return (
    <div style={styles.page}>
      {/* Glow Orbs */}
      <div style={{ ...styles.glow, top: "15%", left: "8%" }} />
      <div style={{ ...styles.glow, bottom: "20%", right: "12%" }} />

      <div style={styles.container}>
        {/* LEFT – CONTEXT */}
        <div style={styles.left}>
          <div style={styles.step}>FINAL STEP</div>
          <h1 style={styles.heading}>Upload pharmacy bill</h1>

          <p style={styles.description}>
            Upload the final bill generated by your pharmacy. This bill will be
            verified against the prescription to ensure exact medicine delivery.
          </p>

          <div style={styles.trustBox}>
            <p>✔ Prescription & bill must match</p>
            <p>✔ Pharmacy name will be verified</p>
            <p>✔ Order locked after verification</p>
          </div>
        </div>

        {/* RIGHT – ACTION */}
        <div style={styles.right}>
          <h2 style={styles.formTitle}>Bill document</h2>

          <div style={styles.uploadBox}>
            <input
              type="file"
              onChange={(e) => setBill(e.target.files[0])}
              style={styles.file}
            />
          </div>

          <button
            style={{
              ...styles.cta,
              opacity: bill ? 1 : 0.6,
            }}
            disabled={!bill}
            onClick={() => setVerified(true)}
          >
            Verify bill & mark ready
          </button>

          {verified && (
            <div style={styles.success}>
              ✅ Bill verified successfully. Order is ready for delivery.
            </div>
          )}

          <p style={styles.note}>
            Once verified, bill and order details cannot be changed.
          </p>
        </div>
      </div>
    </div>
  );
};

const styles = {
  /* PAGE */
  page: {
    minHeight: "100svh",
    position: "relative",
    overflow: "hidden",
    background:
      "radial-gradient(circle at top left, #0d47a1, #020617 60%)",
    fontFamily: "Inter, system-ui, sans-serif",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "48px",
  },

  /* GLOW */
  glow: {
    position: "absolute",
    width: "360px",
    height: "360px",
    background:"#0d47a1",
    filter: "blur(120px)",
    borderRadius: "50%",
    zIndex: 0,
  },

  /* CONTAINER */
  container: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    maxWidth: "1100px",
    display: "flex",
    borderRadius: "22px",
    overflow: "hidden",
    background: "rgba(255,255,255,0.10)",
    backdropFilter: "blur(18px)",
    border: "1px solid rgba(255,255,255,0.18)",
    boxShadow: "0 30px 80px rgba(0,0,0,0.5)",
  },

  /* LEFT */
  left: {
    width: "42%",
    padding: "44px",
    background: "rgba(255,255,255,0.06)",
    borderRight: "1px solid rgba(255,255,255,0.12)",
    color: "#fff",
  },

  step: {
    fontSize: "12px",
    letterSpacing: "0.15em",
    opacity: 0.8,
    marginBottom: "14px",
  },

  heading: {
    fontSize: "30px",
    fontWeight: "700",
    marginBottom: "16px",
  },

  description: {
    fontSize: "15px",
    lineHeight: "1.7",
    opacity: 0.85,
    marginBottom: "26px",
  },

  trustBox: {
    fontSize: "14px",
    lineHeight: "1.9",
    color: "rgba(255, 255, 255, 1)",
  },

  /* RIGHT */
  right: {
    width: "58%",
    padding: "44px",
    color: "#fff",
  },

  formTitle: {
    fontSize: "22px",
    marginBottom: "22px",
  },

  uploadBox: {
    background: "rgba(255,255,255,0.12)",
    padding: "20px",
    borderRadius: "14px",
    border: "1px dashed rgba(255,255,255,0.35)",
    marginBottom: "22px",
  },

  file: {
    color: "#fff",
  },

  cta: {
    width: "100%",
    padding: "16px",
    borderRadius: "14px",
    border: "none",
    background: "linear-gradient(135deg,#42a5f5,#1e88e5)",
    color: "#fff",
    fontSize: "15px",
    cursor: "pointer",
  },

  success: {
    marginTop: "20px",
    background: "rgba(46, 125, 50, 0.25)",
    padding: "16px",
    borderRadius: "14px",
    color: "#a5d6a7",
    fontSize: "14px",
    fontWeight: "600",
    border: "1px solid #0d47a1",
  },

  note: {
    marginTop: "14px",
    fontSize: "13px",
    opacity: 0.75,
  },
};

export default ChemistBillUpload;
